name: making new TOC
on: 
  pull_request:
    branches:
    - TSE_dev
jobs:
  mk-toc:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [2.7]
    steps:
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - uses: actions/checkout@v2
    - name: Making TOC
      run: |
        cd $GITHUB_WORKSPACE
        cd tools/
        python mk_toc.py 
        git diff ../README.md
    - name: Pushes test file
      uses: dmnemec/copy_file_to_another_repo_action@v1.0.4
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_file: ${{github.workspace}}/README.md
        destination_repo: ${{ github.repository }}
        user_email: "1803001@narlabs.org.tw"
        user_name: "NCHC-InfraServ"